version: '2'
services:

    publicweb-publicweb-test:
        build:
            context: .
            dockerfile: Dockerfile     
        image:  gavinjonespf/docker-publicweb-base:${BUILD_TAG}

